import { describe, expect, it } from "vitest";
import type { RequestContext, ToolInvocation } from "../src/contracts/index.ts";
import { HmacApprovalTokenService } from "../src/mutation/approval-token.ts";
import { AllowAllMutationBusinessValidator, InMemoryMutationAuditSink, InMemoryMutationPermissionService, InMemoryMutationPolicyRegistry, InMemoryMutationProposalRepository, InMemoryMutationStore } from "../src/mutation/in-memory.ts";
import { MutationRuntime } from "../src/mutation/runtime.ts";
import type { MutationScope } from "../src/mutation/types.ts";
const scope:MutationScope={userId:"u",tenantId:"t",companyId:"c",projectId:"p"}; const ctx:RequestContext={traceId:"t1",requestId:"r",conversationId:"c",...scope,createdAt:"2026-09-12T00:00:00Z"};
function setup(now=()=>new Date("2026-09-12T00:00:00Z")){ let n=0; const store=new InMemoryMutationStore([{scope,record:{entityType:"X",entityId:"1",version:"1",data:{name:"A"}}}],now); const permissions=new InMemoryMutationPermissionService(); for(const p of ["mutation.prepare","mutation.commit","x.update"])permissions.grant(scope,p); const proposals=new InMemoryMutationProposalRepository(); const runtime=new MutationRuntime({policies:new InMemoryMutationPolicyRegistry([{entityType:"X",createPermission:"x.create",updatePermission:"x.update",deletePermission:"x.delete",softDelete:true}]),permissions,validator:new AllowAllMutationBusinessValidator(),readRepository:store,writeGateway:store,proposals,approvals:store,approvalTokens:new HmacApprovalTokenService("0123456789abcdef0123456789abcdef"),audit:new InMemoryMutationAuditSink(),idFactory:()=>`n${++n}`,now,approvalTtlMs:1000}); return {runtime,store,permissions,proposals}; }
function inv(name:string,args:Record<string,unknown>,context=ctx):ToolInvocation{return{toolCallId:name,toolName:name,toolVersion:"1.0.0",args,context};}
describe("mutation security",()=>{
	it("rejects LLM scope override arguments",async()=>{const {runtime}=setup();const result=await runtime.execute(inv("prepare_update",{entityType:"X",entityIds:["1"],patch:{name:"B"},projectId:"other"}));expect(result.error?.code).toBe("MUTATION_VALIDATION_ERROR");});
	it("rejects token used from another server-bound scope",async()=>{const {runtime}=setup();const p=await runtime.execute(inv("prepare_update",{entityType:"X",entityIds:["1"],patch:{name:"B"}}));const op=(p.data as {proposal:{operationId:string}}).proposal.operationId;const approval=await runtime.approve(op,ctx,true);const other={...ctx,projectId:"other"};const result=await runtime.execute(inv("commit_mutation",{operationId:op,approvalToken:approval.approvalToken},other));expect(result.error?.code).toBe("TOOL_ACCESS_DENIED");});
	it("rejects tampered approval signatures",async()=>{const {runtime}=setup();const p=await runtime.execute(inv("prepare_update",{entityType:"X",entityIds:["1"],patch:{name:"B"}}));const op=(p.data as {proposal:{operationId:string}}).proposal.operationId;const approval=await runtime.approve(op,ctx,true);const bad=approval.approvalToken.slice(0,-1)+(approval.approvalToken.endsWith("A")?"B":"A");const result=await runtime.execute(inv("commit_mutation",{operationId:op,approvalToken:bad}));expect(result.error?.code).toBe("MUTATION_APPROVAL_INVALID");});
	it("rejects expired approval tokens",async()=>{let current=new Date("2026-09-12T00:00:00Z");const x=setup(()=>current);const p=await x.runtime.execute(inv("prepare_update",{entityType:"X",entityIds:["1"],patch:{name:"B"}}));const op=(p.data as {proposal:{operationId:string}}).proposal.operationId;const approval=await x.runtime.approve(op,ctx,true);current=new Date("2026-09-12T00:00:02Z");const result=await x.runtime.execute(inv("commit_mutation",{operationId:op,approvalToken:approval.approvalToken}));expect(result.error?.code).toBe("MUTATION_APPROVAL_EXPIRED");});
	it("rejects proposal tampering after approval",async()=>{const x=setup();const p=await x.runtime.execute(inv("prepare_update",{entityType:"X",entityIds:["1"],patch:{name:"B"}}));const op=(p.data as {proposal:{operationId:string}}).proposal.operationId;const approval=await x.runtime.approve(op,ctx,true);const stored=await x.proposals.get(op);if(!stored)throw new Error("missing proposal");await x.proposals.update({...stored,digest:"0".repeat(64)});const result=await x.runtime.execute(inv("commit_mutation",{operationId:op,approvalToken:approval.approvalToken}));expect(result.error?.code).toBe("MUTATION_DIGEST_MISMATCH");});

});
